In [8]:
import autograd.numpy as np
from autograd import grad
import random

In [9]:
def initPerceptronNetwork(nInputs, layers, outputs):
    network = []
    
    layers = np.append(layers, outputs)
    prevSize = nInputs
    for size in layers:
        L = []
        
        for i in range(0, size):
            L.append(-0.5 + np.random.rand(prevSize+1))
            
        network.append(L)
        prevSize = size
        
    return network
        
def f(network, d):
    inputs = d
    for l in range(0, len(network)):
        inputs = np.array([np.sum(m(inputs, neuron)) for neuron in network[l]])
        
    return inputs

def m(v1, v2):
    res = [None] * max(len(v1), len(v2))
    for i in range(0, max(len(v1), len(v2))):
        a = v1[i] if i < len(v1) else None
        b = v2[i] if i < len(v2) else None
        
        if a and b:
            res[i] = a * b
        elif a:
            res[i] = a
        else:
            res[i] = b
    return res
            
        
            

In [10]:
def __loss__(net):
    err = 0
    
    for i in range(0, R.shape[0]):
        for j in range(0, R.shape[1]):
            if R[i,j] == 0:
                continue
                
            u_i = R[i,:] # I'th row is the user
            m_i = R[:,j] # J'th colum is the movie
                
            inputs = np.concatenate([u_i, m_i])
                
            r_ij = f(net, inputs)
            err += np.power((R[i,j] - r_ij), 2)
            
    return err

def R_hat(net):
    R_hat = np.zeros(R.shape)
    for i in range(0, R.shape[0]):
        for j in range(0, R.shape[1]):
            u_i = R[i,:] # I'th row is the user
            m_i = R[:,j] # J'th colum is the movie
                
            inputs = np.concatenate([u_i, m_i])
            R_hat[i][j] = f(net, inputs)
            
    return R_hat

def applyGrad(network, grad, LR):
    for l in range(0, len(network)):
        network[l] -= LR * np.array(grad[l])

# Example

In [14]:
# R = np.array([
#     [1.0,4.0,3.0,6.0],
#     [6.0,3.0,8.0,1.0],
#     [2.0,7.0,5.0,3.0],
#     [2.0,6.0,4.0,3.0]
# ])

A = np.array(
[
    [1,2,1],
    [2,4,3],
    [1,5,4]
])

B = np.array(
[
    [1,2,1],
    [1,4,2],
    [4,5,4]
])

R = np.dot(A, B)


print("-- R --")
print(R)

R[1,2] = 0
R[2,1] = 0
R[0,0] = 0

theta_grad = grad(__loss__)

theta = initPerceptronNetwork(6, [6], 1)

LR = 0.000001

for i in range(0, 5001):
    if i % 100 == 0:
        print("[" + str(i) +"]: " + str(__loss__(theta)))
        
    theta_g = theta_grad(theta)
    applyGrad(theta, theta_g, LR)
    
    
print("-- R0 --")
print(R)
print("\n-- R Hat --")
print(R_hat(theta))

-- R --
[[ 7 15  9]
 [18 35 22]
 [22 42 27]]
[0]: [ 4984.42700997]
[100]: [ 408.00590938]
[200]: [ 294.61493194]
[300]: [ 244.58210808]
[400]: [ 209.45667459]
[500]: [ 183.1425204]
[600]: [ 162.59776076]
[700]: [ 146.08030279]
[800]: [ 132.48708761]
[900]: [ 121.06808537]
[1000]: [ 111.29136502]
[1100]: [ 102.77180895]
[1200]: [ 95.22844084]
[1300]: [ 88.45602888]
[1400]: [ 82.30485353]
[1500]: [ 76.66580322]
[1600]: [ 71.45928039]
[1700]: [ 66.62695907]
[1800]: [ 62.12570625]
[1900]: [ 57.92314077]
[2000]: [ 53.99441974]
[2100]: [ 50.31993484]
[2200]: [ 46.88367608]
[2300]: [ 43.67208047]
[2400]: [ 40.67323081]
[2500]: [ 37.87630536]
[2600]: [ 35.27120687]
[2700]: [ 32.84831895]
[2800]: [ 30.59835257]
[2900]: [ 28.51225572]
[3000]: [ 26.58116693]
[3100]: [ 24.79639841]
[3200]: [ 23.14943887]
[3300]: [ 21.63196829]
[3400]: [ 20.23587946]
[3500]: [ 18.9533023]
[3600]: [ 17.77662823]
[3700]: [ 16.69853269]
[3800]: [ 15.71199465]
[3900]: [ 14.81031225]
[4000]: [ 13.98711437]
[4100]: [ 13.