In [2]:
import numpy as np
import random
LEARNING_RATE = 0.0002

In [7]:
def factoriseMatrix(R, lf, steps=5000):
    U = R.shape[0]
    D = R.shape[1]
    
    P = np.random.rand(U, lf)
    Q = np.transpose(np.random.rand(D, lf))
    
    for step in range(0, steps):
        R_hat = np.dot(P, Q)
        P_delta = np.zeros(P.shape)
        Q_delta = np.zeros(Q.shape)
        
        for i in range(0, U):
            for j in range(0, D):
                # Skip if entrie is missing
                if not R[i][j] > 0:
                    continue
                
                e = R[i][j] - np.dot(P[i,:],Q[:,j])
                for k in range(0, lf):
                    P_delta[i,k] += e * Q[k, j]
                    Q_delta[k,j] += e * P[i, k]
                    
        P = P + 2 * LEARNING_RATE * P_delta
        Q = Q + 2 * LEARNING_RATE * Q_delta
    
    return P, Q

def loss(R, R_hat):
    D = R - R_hat
    err = 0
    
    for i in range(D.shape[0]):
        for j in range(D.shape[1]):
            if not R[i][j] > 0:
                continue
                
            err += np.power(D[i][j], 2)
            
    return err

# Tests

In [8]:
A = np.array(
[
    [1,2,1,4],
    [2,4,3,1],
    [1,5,4,2],
    [2,4,4,3]
])

B = np.array(
[
    [1,2,1,4],
    [1,4,6,1],
    [4,5,4,2],
    [1,2,4,1],
])

R = np.dot(A, B)

print("-- R --")
print(R)

R[1,2] = 0
R[2,1] = 0
R[0,0] = 0

print("-- R0 --")
print(R)

A_hat, B_hat = factoriseMatrix(R, 4, 50000)
R_hat = np.dot(A_hat, B_hat)

print("\n-- A Hat --")
print(A_hat)

print("\n-- B Hat --")
print(B_hat)

print("\n-- R Hat --")
print(R_hat)

-- R --
[[11 23 33 12]
 [19 37 42 19]
 [24 46 55 19]
 [25 46 54 23]]
-- R0 --
[[ 0 23 33 12]
 [19 37  0 19]
 [24  0 55 19]
 [25 46 54 23]]

-- A Hat --
[[ 3.12366314  1.04041461  2.26799095  0.33223005]
 [ 2.96362246  2.04841092  2.90642785  3.00629383]
 [ 5.32722771  2.51471195  3.04531728  0.34751907]
 [ 4.54301712  2.96866661  3.16145184  2.88037003]]

-- B Hat --
[[ 2.67766047  3.72429022  6.61156503  1.81073723]
 [ 1.5355032   3.01804588  2.94524884  0.91342693]
 [ 1.83023044  3.10283462  3.95509462  2.1027476 ]
 [ 0.86473618  3.57990516  0.94301906  1.87975658]]

-- R Hat --
[[ 14.3999067   23.          33.          12.        ]
 [ 19.          37.00000001  39.95745202  18.99999999]
 [ 24.          38.12285928  55.          19.        ]
 [ 25.          45.99999999  54.          23.00000001]]


In [ ]:
# 3 X 4
R = np.array(
    [[1, 2, 3, 0],
     [5, 0, 4, 1],
     [3, 4, 1, 0]])

P, Q = factoriseMatrix(R, 2, 30000)
R_hat = np.dot(P, Q)
print("Err: " + str(loss(R, R_hat)))
print(R_hat)